### ISSUE TITLE
Cannot read properties of null (reading 'popupTitle')

### ISSUE THREAD

**Issue by alessandroderomawep** [HyperSense-Software/hss-okta-flutter#33]
Code is pretty straightforward:

```
import 'package:hss_okta_flutter/hss_okta_flutter.dart'

Future<void> login() async {
  final oktaWeb = HssOktaFlutterWeb();
  await oktaWeb.initializeClient(
      oktaConfig: OktaConfig(
      issuer: '...',    // removed
      clientId: '...', // removed
      redirectUri: Uri.base.toString(),
    ),  
  );

  // readme says to use await oktaWeb.token.startPopUpAuthentication, 
  // but the compiler complains about "token" not existing in object oktaWeb,
  // so I'm using this instead
  await oktaWeb.startPopUpAuthentication();
}
```

This is the error I get:

```
browser.ts:43 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'popupTitle')
    at t.loadPopup (browser.ts:43:23)
    at t.getWithPopup (getWithPopup.ts:27:23)
    at e.value (PromiseQueue.ts:78:32)
    at PromiseQueue.ts:64:12
    at new Promise (<anonymous>)
    at e.value (PromiseQueue.ts:46:12)
    at hss_okta_flutter_web.HssOktaFlutterWeb.new.startPopUpAuthentication (hss_okta_flutter_web.dart:58:57)
    at startPopUpAuthentication.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:127:5)
    at hss_okta_flutter_web.HssOktaFlutterWeb.new.startPopUpAuthentication (hss_okta_flutter_web.dart:55:49)
    at login_service.LoginService.new.login (login_service.dart:54:19)
    at login.next (<anonymous>)
    at async_patch.dart:45:50
    at _RootZone.runUnary (zone.dart:1661:54)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:162:18)
    at handleValueCallback (future_impl.dart:846:44)
    at _Future._propagateToListeners (future_impl.dart:875:13)
    at [_completeWithValue] (future_impl.dart:647:5)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:721:7)
    at Object._microtaskLoop (schedule_microtask.dart:40:11)
    at _startMicrotaskLoop (schedule_microtask.dart:49:5)
    at async_patch.dart:181:7
```

I did insert the okta script in the header block of index.html as the readme suggests and the okta library loads successfully.

Using `startRedirectAuthentication()` works as expected.

---

```
flutter --version

Flutter 3.16.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 78666c8dc5 (2 weeks ago) • 2023-12-19 16:14:14 -0800
Engine • revision 3f3e560236
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Comment by xhirazi** [comment]
+1

**Comment by vinceramcesoliveros-hypersensesoftware** [comment]
Hello @alessandroderomawep. Can you add AuthorizeOptions inside the oktaWeb.startPopUpAuthentication?


```dart
await oktaWeb.startPopUpAuthentication(
  options: AuthorizeOptions(
    responseType: ['token', 'id_token'],
    scopes: ['openid', 'email', 'profile'],
  ),
);
```

**Comment by aldrin233** [comment]
Will be closing this due to inactivity

**Comment by alessandroderomawep** [comment]
Works with the provided example
